server:
    port: 8080    
    servlet:
        contextPath: /api/v2/loyalty

spring:    
    main:
        allow-bean-definition-overriding: true
    application:
        name: "comerzzia api v2 for loyalty"
    messages:
        basename: i18n/messages,i18n/loyalty-messages
    jackson:
       serialization:
          FAIL_ON_EMPTY_BEANS: false
        
    quartz:
       job-store-type: jdbc
       scheduler-name: loyalty
       properties: 
          org.quartz.threadPool.threadCount: 5
          org.quartz.jobStore.misfireThreshold: 60000
          org.quartz.jobStore.isClustered: true
          org.quartz.scheduler.instanceId: AUTO

management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: "/manage"        
      exposure:
        include: "*" # "health,info"
                  
logging:
    level:
        ROOT: ${LOG_LEVEL:INFO}
        com.comerzzia: ${LOG_LEVEL:INFO} 
        com.comerzzia.api: ${LOG_LEVEL:INFO} 
        org.mybatis: INFO   
        org.springframework : INFO