stages:
  - maven
  - build-containers
  - deploy-containers
  
image: maven:3.6-jdk-8-slim

variables:
  GIT_SUBMODULE_STRATEGY: normal
  DOCKER_IMAGE: clientes/dinosol/comerzzia/api/v2/loyalty
  MAVEN_OPTS: "-Djava.awt.headless=true -Dmaven.repo.local=.m2/repository"  
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode --errors --fail-at-end --show-version"
  K8S_WORKLOAD: api-v2-loyalty
  K8S_NAMESPACE: dinosol
  
  DOCKER_IMAGE_TIER1: comerzzia/api/v2/loyalty
  DOCKER_IMAGE_CLIENT: clientes/dinosol/comerzzia/api/v2/loyalty
  
  DOCKER_IMAGE_DEV: $DEVELOP_REGISTRY_SERVER/$CLIENT/$DOCKER_IMAGE_TIER1
  DOCKER_IMAGE_CLIENT_PRO: $REGISTRY_SERVER_CLIENT_PRO/$DOCKER_IMAGE_CLIENT
  
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - .m2/repository
  
build_maven:
  stage: maven
  only:
  - master
  - develop
  - tags
  - branches
  before_script:
  - export BUILD_DATE=$(TZ="Europe/Madrid" \date +"%d-%m-%Y %H:%M:%S")
  script:
  - mvn $MAVEN_CLI_OPTS package -DskipTests  
  artifacts:
    paths:
    - services/target/*.jar
    - application/target/*.war    
    expire_in: 1 hour

    
docker_build:
  stage: build-containers
  dependencies:
  - build_maven
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
  ### create kaniko credentials file
  - cp "$KANIKO_SECRET" /kaniko/.docker/config.json
  script: >
    if [[ ! -z "$CI_COMMIT_TAG" ]]; then
      echo Building image "${DOCKER_IMAGE_DEV}:$CI_COMMIT_TAG && ${DOCKER_IMAGE_CLIENT_PRO}:$CI_COMMIT_TAG"
      /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/application/src/main/docker/Dockerfile" --destination "${DOCKER_IMAGE_DEV}:$CI_COMMIT_TAG" --destination "${DOCKER_IMAGE_CLIENT_PRO}:$CI_COMMIT_TAG"
    else
      echo Building image "${DOCKER_IMAGE_DEV}:$CI_COMMIT_BRANCH && ${DOCKER_IMAGE_CLIENT_PRO}:$CI_COMMIT_BRANCH"
      /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/application/src/main/docker/Dockerfile" --destination "${DOCKER_IMAGE_DEV}:$CI_COMMIT_BRANCH" --destination "${DOCKER_IMAGE_CLIENT_PRO}:$CI_COMMIT_BRANCH"
    fi
  rules:
    - if: ($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH )
    - if: ($CI_COMMIT_TAG != null)

# Realizar redeploy en Kubernetes a trav√©s de rancher a DESARROLLO  
deploy_latest:
  stage: deploy-containers
  only:
  - develop
  when: manual
  dependencies:
  - docker_build
  image: $TR1_REGISTRY_SERVER/contrib/rancher-cli-k8s
  script:
    - rancher login $RANCHER_SERVER --token $RANCHER_TOKEN --context $RANCHER_PROJECT_CLIENTES
    - rancher kubectl patch deployment $K8S_WORKLOAD -n $K8S_NAMESPACE -p '{"spec":{"template":{"metadata":{"labels":{"date":"'`date +'%s'`'", "vcs-commit":"'$CI_COMMIT_SHA'" }}}}}'

